name: 'O365 FileHandler Workflow'

on:
  push:
    paths: 
      - 'Online/glasswall.o365.filehandler/Net5/**'
    
  workflow_dispatch:
    paths: 
      - 'Online/glasswall.o365.filehandler/Net5/**'


defaults:
  run:
    working-directory: './Online/glasswall.o365.filehandler/Net5'

jobs:
  e2e:
    name: 'E2E FileHandler Test' 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './Online/o365-filehandler-tests/filehandler-tests'
    environment: GW-DEV
    env:
      SP_URL: ${{ secrets.SPO_URL }}
      SP_USER: ${{ secrets.SPO_USER }}
      SP_USER_PWD: ${{ secrets.SPO_USER_PWD }}
      SITE_NAME: ${{ secrets.SPO_SITE_NAME }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - run: npm install -g @getgauge/cli
      name: Install Gauge

    - run: npm install
      name: Install dependencies

    - run: npm run test-ci
      name: Run E2E tests
    