name: 'O365 HideDownloadExtension Release Workflow'

on:
  release:
    types: [published]

env:
  SPPKG_FILE_NAME: 'glasswall-hide-download-ext.sppkg'

defaults:
  run:
    working-directory: './Online/glasswall-hide-download-ext'

jobs:
  build:
    name: 'Build Extension'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Use Node.js 10.x
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 10.x
    
    - name: Run npm ci
      run: npm ci
    
    - name: Run npm i -g gulp
      run: sudo npm i -g gulp
      if: runner.os == 'macOS'
    
    - name: Bundle and package
      run: |
        gulp clean
        gulp bundle --ship
        gulp package-solution --ship    


    - name: Zip artifacts
      run: zip -r -q ./sharepoint/solution/GWO365Extensions.zip ./sharepoint/solution/glasswall-hide-download-ext.sppkg        
        

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./sharepoint/solution/*.zip"]'